export const SUPPORTED_LOCALES = ['en', 'zh-CN'];
export const DEFAULT_LOCALE = 'en';

const ESCAPE_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };

export function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ESCAPE_MAP[character]);
}

// Every locale in one tuple, so a missing translation fails loudly instead
// of hiding behind an English fallback.
const MESSAGE_PAIRS = {
  'diagram.description.architecture': ['A system architecture diagram generated by Dev-Strom.', '由 Dev-Strom 生成的系统架构图。'],
  'node.focus': ['Focus {label}', '聚焦{label}'],
  'node.focus.detail': ['Focus {label}, {detail}', '聚焦{label}，{detail}'],
  'node.context.architecture': ['Architecture component', '架构组件'],
  'legend.title': ['Legend', '图例'],
  'legend.architecture.frontend': ['Frontend', '前端'],
  'legend.architecture.backend': ['Backend', '后端'],
  'legend.architecture.database': ['Database', '数据库'],
  'legend.architecture.cloud': ['Cloud', '云服务'],
  'legend.architecture.security': ['Security', '安全'],
  'legend.architecture.messagebus': ['Message bus', '消息总线'],
  'legend.architecture.external': ['External', '外部系统'],
};

for (const [key, messages] of Object.entries(MESSAGE_PAIRS)) {
  if (messages.length !== SUPPORTED_LOCALES.length || messages.some((message) => typeof message !== 'string')) {
    throw new Error(`Incomplete i18n tuple ${JSON.stringify(key)}`);
  }
}

const CATALOGS = Object.fromEntries(SUPPORTED_LOCALES.map((locale, index) => [
  locale,
  Object.fromEntries(Object.entries(MESSAGE_PAIRS).map(([key, pair]) => [key, pair[index]])),
]));

export function resolveLocale(locale) {
  return SUPPORTED_LOCALES.includes(locale) ? locale : DEFAULT_LOCALE;
}

function formatMessage(template, values = {}) {
  return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => (
    Object.hasOwn(values, key) ? String(values[key]) : match
  ));
}

export function translateMessage(locale, key, values = {}) {
  const resolved = resolveLocale(locale);
  if (!Object.hasOwn(CATALOGS[resolved], key)) {
    throw new Error(`Missing i18n message ${JSON.stringify(key)} for ${resolved}`);
  }
  return formatMessage(CATALOGS[resolved][key], values);
}
